### PR TITLE
allow passing in a list of urls to ignore to the crawler

### PR DESCRIPTION
**Pull request by andybak**

### CODE REVIEW

**Comment by andybak** [comment]
I notice you haven't updated this repo in a while. I'm happy to take it over. If you're happy then I'll create a Github group just for this project to ease future transfers.

**Comment by ojii** [comment]
nice change and thanks for offering to take over maintenance. Could you please tell me your PyPI username so I can give you access to that too?

**Comment by andybak** [comment]
Sure. It's andybak

I've created an org and invited you. I think if you transfer the repo Github will handle redirects correctly: https://github.com/blog/1508-repository-redirects-are-here

**Comment by ojii** [comment]
done, closing this.

**Comment by andybak** [comment]
How did you transfer the repo across? It's lost all it's history.

**Comment by ojii** [comment]
what the heck, I've done it how I've always done it (via the "Transfer Repo" button in settings). Luckily you have a fork so you can push the history back to where it belongs

**Comment by andybak** [comment]
Any idea how to do that without recreating the repo (and possibly breaking redirects)?

I was hoping:

```
git push upstream --mirror
```

might do it...

**Comment by ojii** [comment]
did this actually have any history?

**Comment by andybak** [comment]
Lol. Nope. That possibility hadn't actually occurred to me!

**Pull request closed without merging**
